name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Composer Install
        run: composer install
      - name: Run Tests
        run: make test-ci
      - name: Check Test Coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "98"
          filename: "./clover.xml"
      - name: Upload Coverage on Failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: clover-coverage
          path: coverage
      - name: Run PHPStan
        run: make stan-ci
